name: nicu-fluid-management
region: us-central1
env: standard
runtime: python310
instance_class: F2

entrypoint: gunicorn -b :$PORT src.web_server:app

env_variables:
  FLASK_APP: "src/web_server.py"
  FLASK_ENV: "production"
  SECRET_KEY: "change-this-in-production"
  DATABASE_URL: "sqlite:///nicu_app.db"

handlers:
- url: /static
  static_dir: src/static

- url: /.*
  script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 5
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
